services:
  proxy:
    image: nginx:alpine
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
  backend:
    build:
      context: backend
