name: Build / Push Docker Image to Registry

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build / Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h-takeyeah
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker Image Tag
        # https://qiita.com/yu-ichiro/items/c1a1248c0cdeeb0e6b42
        run: |
          SHA=${{ github.sha }}
          TAG=$(TZ=UTC-9 date "+%Y%m")-${SHA:0:7}
          echo "DOCKER_IMAGE_TAG_CI=$TAG" >> $GITHUB_ENV
          echo TAG $TAG
      - name: Docker Buildx Bake
        uses: docker/bake-action@v4
        with:
          workdir: docker-compose-build
          files: compose.ci.yaml
          push: true
