name: Build / Push Docker Image to Registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build / Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h-takeyeah
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=edge
            type=sha,format=short,prefix=
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=Containernized helloworld written in Go
          annotations: |
            org.opencontainers.image.description=Containernized helloworld written in Go
      - name: Docker Buildx Bake
        uses: docker/bake-action@v6
        with:
          source: .
          workdir: docker-compose-build
          # filesについて
          # - 下に書いてあるようにlabelesとtagsを一緒にしたbake-fileを使うのがベター
          #
          # - もしbake-file-*を個別に渡すときは今回docker-bake.hclの中でtagを参照している
          #   のでbake-file-tagsがリストの最後に来るようにする必要がある
          #   (tags以外が最後に来るとtags==nullなtargetで上書きされてしまう)
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          push: true
          set: |
            *.cache-from=type=gha,scope=image
            *.cache-to=type=gha,scope=image
