name: Build / Push Docker Image to Registry

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build / Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h-takeyeah
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker Image Tag
        # https://qiita.com/yu-ichiro/items/c1a1248c0cdeeb0e6b42
        run: |
          TAG=$(TZ=UTC-9 date "+%Y%m")-${GITHUB_SHA:0:7}
          echo "DOCKER_IMAGE_TAG_CI=$TAG" >> $GITHUB_ENV
          echo TAG $TAG
      - name: Prepare Labels
        id: label-generator
        run: |
          echo ORG_OPENCONTAINER_IMAGE_CREATED="$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT
          echo ORG_OPENCONTAINER_IMAGE_VERSION="$(echo $GITHUB_REF_NAME | sed 's/^v//')" >> $GITHUB_OUTPUT
      - name: Docker meta
        uses: docker/metadata-action@v5
      - name: Upload metadatafile
        uses: actions/uploatd-artifact@v4
        with:
          path: |
            cwd://${{ steps.meta.outputs.bake-file-tags }}
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
      - name: Docker Buildx Bake
        uses: docker/bake-action@v6
        with:
          source: .
          workdir: docker-compose-build
          files: |
            compose.ci.yaml
            cwd://${{ steps.meta.outputs.bake-file-tags }}
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
          push: true
