name: Deploy Containers

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: run docker compose up
        shell: bash
        working-directory: docker-example
        run: |
          docker compose up -d --build
