name: Build yarn project

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: yarn-project-sample

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
      # > enable corepack before setup-node.
      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: yarn-project-sample

      - name: Install dependencies
        run: yarn
      # TODO: build
